name: Rust

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Run lint
      uses: github/super-linter@v4   
      env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      run: cargo test --verbose      
    - name: Build
      run: cargo build --verbose
